;------------------------------------------------------------------------------
;
;	Thorin.ini
;
;------------------------------------------------------------------------------

; aka Thorin, Dwarf
Object DwarvenThorin
	; *** ART Parameters ***
	SelectPortrait                                = HPEreborThorin
	ButtonImage                                   = HIEreborThorin 
	MaxSimultaneousOfType                         = 1
	ShadowMaxHeight                               = 999
	Scale  										                    = .99

	; -- Draw Module

	; -- Draw Module END 

  ; ***DESIGN parameters ***
  Side                                        = Dwarven
  EditorSorting                               = UNIT
  ThreatLevel                                 = 5.0
  TransportSlotCount                          = 1
  BuildCost                                   = THORIN_BUILDCOST					
  BuildTime                                   = THORIN_BUILDTIME
  DisplayMeleeDamage                          = THORIN_DAMAGE
  HeroSortOrder                               = 40
        
  WeaponSet
    Conditions                                = None 
    Weapon                                    = PRIMARY  ThorinSword  
    AutoChooseSources                         = PRIMARY FROM_PLAYER FROM_SCRIPT FROM_AI
  End
  
  WeaponSet
    Conditions                                = WEAPONSET_TOGGLE_1
    Weapon                                    = SECONDARY  ThorinSword2
    AutoChooseSources                         = SECONDARY FROM_PLAYER FROM_SCRIPT FROM_AI
  End
  
  ArmorSet
    Conditions                                = None
    Armor                                     = ToughHeroArmor
    DamageFX                                  = NormalDamageFX
  End
  
  VisionRange                                 = VISION_STANDARD_MELEE				
  ShroudClearingRange                         = SHROUD_CLEAR_STANDARD
  BountyValue                                 = THORIN_BOUNTY_VALUE
  DisplayName                                 = OBJECT:DwarvenThorin
  RecruitText                                 = CONTROLBAR:DwarvenThorinRecruit
  ReviveText                                  = CONTROLBAR:DwarvenThorinRevive
  Hotkey                                      = CONTROLBAR:DwarvenThorinHotkey
  CrushableLevel                              = 2  ;What am I?:        0= for infantry, 1= for trees, 2= general vehicles
  CommandSet                                  = DwarvenThorinCommandSet
  CommandPoints                               = 0

  ; *** AUDIO Parameters ***;

  VoiceAttack					                          = ThorinVoiceAttack
  VoiceAttackStructure			                    = ThorinVoiceAttackBuilding
  VoiceAttackMachine			                      = ThorinVoiceAttack
  VoiceAttackCharge				                      = ThorinVoiceAttackCharge
  VoiceEnterStateAttack			                    = ThorinVoiceEnterStateAttack
  VoiceEnterStateAttackStructure	              = ThorinVoiceEnterStateAttackBuilding
  VoiceEnterStateAttackMachine		              = ThorinVoiceEnterStateAttack
  VoiceEnterStateAttackCharge		                = ThorinVoiceEnterStateAttackCharge
  VoiceFear 					                          = ThorinVoiceHelpMe
  VoiceMove					                            = ThorinVoiceMove
  VoiceMoveToCamp				                        = ThorinVoiceMoveCamp
  VoiceMoveWhileAttacking			                  = ThorinVoiceDisengage
  VoiceEnterStateMove			                      = ThorinVoiceEnterStateMove
  VoiceEnterStateMoveToCamp		                  = ThorinVoiceEnterStateMoveCamp
  VoiceEnterStateMoveWhileAttacking	            = ThorinVoiceEnterStateDisengage
  VoicePriority				                          = 100
  VoiceRetreatToCastle			                    = ThorinVoiceRetreat
  VoiceEnterStateRetreatToCastle	              = ThorinVoiceEnterStateRetreat
  VoiceSelect					                          = ThorinVoiceSelect
  VoiceSelectBattle				                      = ThorinVoiceSelectBattle
  VoiceGuard					                          = ThorinVoiceMove
  SoundImpact					                          = ImpactHorse
    
  UnitSpecificSounds
    VoiceGarrison                             = ThorinVoiceMoveGarrison
  End

  EvaEventDamagedOwner                        = UnitUnderAttack		;Eva event to trigger when unit is damaged

  Behavior                                    = LargeGroupAudioUpdate ModuleTag_LGAU		; Tie into LargeGroupAudio system
    Key                                       = Dwarf Unit Infantry Hero
  End

  ClientBehavior                                = AnimationSoundClientBehavior ModuleTag_AnimAudioBehavior
    MaxUpdateRangeCap                           = 800
    AnimationSound                              = Sound:FootstepDirtA			Animation:DUDain_SKL.DUDain_RUNA	Frames:3 14
    AnimationSound                              = Sound:FootstepDirtA			Animation:DUDain_SKL.DUDain_RUNB	Frames:3 12
    AnimationSound                              = Sound:FootstepDirtA			Animation:DUDain_SKL.Duthorin_RUNA	Frames:3 14
    AnimationSound                              = Sound:FootstepDirtA			Animation:DUDain_SKL.Duthorin_RUNC	Frames:3 12
    
    AnimationSound                              = Sound:BodyFallSoldier			Animation:DUDain_SKL.DUDain_LNDA	Frames:4
    AnimationSound                              = Sound:BodyFallSoldier			Animation:DUDain_SKL.DUDain_DIEA	Frames:11
    AnimationSound                              = Sound:BodyFallSoldier			Animation:DUDain_SKL.DUDain_DIEC	Frames:59
    AnimationSound                              = Sound:BodyFallSoldier			Animation:DUDAIN_SKL.DUDAIN_DTHA	Frames:73
    
    AnimationSound                              = Sound:SwordIntoGround		Animation:DUDAIN_SKL.DUDAIN_IDLE	Frames:61		;striking ground with axe
    AnimationSound                              = Sound:TauntHumanHitShield		Animation:DUDAIN_SKL.DUDAIN_SPCA	Frames:25 50	;hitting shield and sword
    AnimationSound                              = Sound:TauntHumanHitShield		Animation:DUDAIN_SKL.DUDAIN_TNTA	Frames:28 43	;hitting shield and sword
  End

  ; *** ENGINEERING Parameters ***
  RadarPriority                               = UNIT
  KindOf                                      = PRELOAD SELECTABLE CAN_CAST_REFLECTIONS INFANTRY PATH_THROUGH_EACH_OTHER SCORE THROWN_OBJECT GIMLI HERO ARMY_SUMMARY ATTACK_NEEDS_LINE_OF_SIGHT
  PathfindDiameter                            = 40.0
  EvaEventDieOwner                        	    = ThorinDie			;Eva event to trigger on unit's death. NOTICE THAT this is only for permanent deaths
  
  Body                                        = RespawnBody ModuleTag_RespawnBody
    CheerRadius                               = EMOTION_CHEER_RADIUS
    MaxHealth                                 = THORIN_HEALTH  ;BALANCE Gimli Health
    PermanentlyKilledByFilter                 = NONE		;Who kills me permanently?
    DodgePercent                              = 80%	
  End

  Behavior                                    = RespawnUpdate ModuleTag_RespawnUpdate
    DeathAnim                                 = DYING			;Model condition to play when killed-to-respawn
    DeathFX                                   = FX_ThorinDieToRespawn	;FXList to play when killed-to-respawn
    DeathAnimationTime                        = 4100			;How long DeathAnim will take.
    InitialSpawnFX                            = FX_ThorinInitialSpawn
    RespawnAnim                               = LEVELED			;Animation to play when respawning.
    RespawnFX                                 = FX_ThorinRespawn		;FXList to play when respawning.
    RespawnAnimationTime                      = 2000			;Time it takes for respawn to play.
    AutoRespawnAtObjectFilter                 = NONE +CASTLE_KEEP	;Respawn at this location -- and at it's exit production point if possible.
    ButtonImage                               = HIEreborThorin
    
    ;RespawnEntries determine the ruleset for how a character can be revived. Some units may automatically respawn, others
    ;may require a specific revive action performed on him. You can specify different values for each level... or use Level:Any
    RespawnRules                              = AutoSpawn:No	Cost:900		Time:90000		Health:100%		;DEFAULT VALUES
    RespawnEntry                              = Level:2					Cost:1000		Time:90000						;For other levels, only override what is different.
    RespawnEntry                              = Level:3					Cost:1100		Time:90000
    RespawnEntry                              = Level:4					Cost:1200		Time:90000
    RespawnEntry                              = Level:5					Cost:1300		Time:120000
    RespawnEntry                              = Level:6					Cost:1400		Time:150000 ;120000
    RespawnEntry                              = Level:7					Cost:1500		Time:180000 ;120000
    RespawnEntry                              = Level:8					Cost:1600		Time:180000 ;120000
    RespawnEntry                              = Level:9					Cost:1700		Time:180000 ;120000
    RespawnEntry                              = Level:10				Cost:1800		Time:180000 ;120000
  End

  Behavior                                    = AutoHealBehavior ModuleTag_GimliHealing
    StartsActive                              = Yes
    HealingAmount                             = HERO_HEAL_AMOUNT
    HealingDelay                              = 1000
    StartHealingDelay                         = HERO_HEAL_DELAY
    HealOnlyIfNotInCombat                     = Yes
  End
  
  Behavior                                    = AIUpdateInterface ModuleTag_03
    AutoAcquireEnemiesWhenIdle                = Yes ATTACK_BUILDINGS
    MoodAttackCheckRate                       = 500
    HoldGroundCloseRangeDistance              = 60
    AILuaEventsList							              = ThorinFunctions
  End
  
  Behavior                                    = AttributeModifierAuraUpdate ModuleTag_HeroRadiateFear
    StartsActive                              = No ;If no, requires upgrade to turn on.
    BonusName                                 = HeroRadiateFear
    TriggeredBy                               = Upgrade_HeroRadiateFear
    RefreshDelay                              = 2000
    Range                                     = 120
    TargetEnemy                               = Yes
    ObjectFilter                              = ANY +ORC
  End	

  Behavior                                    = AutoAbilityBehavior ModuleTag_AutoAbilityBehavior
  End		

  LocomotorSet
    Locomotor                                 = RohanGimliLocomotor
    Condition                                 = SET_NORMAL 
    Speed                                     = NORMAL_GOOD_HERO_SPEED
  End
;  Locomotor                                  = SET_WANDER HumanWanderLocomotor

  Behavior                                    = PhysicsBehavior ModuleTag_04
    GravityMult                               = 1.0
    AllowBouncing                             = No
    ShockStunnedTimeLow                       = 1400	;msec
    ShockStunnedTimeHigh                      = 2400	;msec
    ShockStandingTime                         = 2600	;msec
  End 

  Behavior                                    = SquishCollide ModuleTag_06
    ;nothing
  End

  Behavior                                    = SlowDeathBehavior ModuleTag_NormalDeath
    DeathTypes                                = NONE +KNOCKBACK
    SinkDelay                                 = 3000
    SinkRate                                  = 0.40     ; in Dist/Sec
    DestructionDelay                          = 8000
  End
  
  Behavior                                    = SlowDeathBehavior ModuleTag_FuckDeath
    DeathTypes                                = ALL -KNOCKBACK
    SinkDelay                                 = 3000
    SinkRate                                  = 0.40     ; in Dist/Sec
    DestructionDelay                          = 8000
    Sound                                     = INITIAL ThorinVoiceDie
  End

  Behavior                                    = EmotionTrackerUpdate	Module_EmotionTracker
    TauntAndPointDistance                     = 300		; max distance to taunted/pointed objet
    TauntAndPointUpdateDelay                  = 1000	; how often scan (milliseconds)
    AddEmotion                                = Alert_Base
  End

  Behavior                                    = HitReactionBehavior HitReactionBehaviorModuleTag
    HitReactionLifeTimer1                     = 2200 ; level 1 (light  damage)  hit reaction animations in frames (5 per sec)
    HitReactionLifeTimer2                     = 15 ; level 2 (medium damage)  hit reaction animations in frames (5 per sec)
    HitReactionLifeTimer3                     = 10 ; level 3 (heavy  damage)  hit reaction animations in frames (5 per sec)

    HitReactionThreshold1                     = 1.0   ; level 1 (light  damage) threshold trigger
    HitReactionThreshold2                     = 2500.0  ; level 2 (medium damage) threshold trigger
    HitReactionThreshold3                     = 5000.0  ; level 3 (heavy  damage) threshold trigger
  End 

  ;--------------------------------------------------------------------------------------------
  ;Behavior                                     = ExperienceLevelCreate ModuleTag_LevelBonus
  ;	LevelToGrant	                              = 10
  ;	MPOnly			                                = Yes
  ;End

  Geometry                                    = CYLINDER
  GeometryMajorRadius                         = 5.6
  GeometryMinorRadius                         = 5.6
  GeometryHeight                              = 16.0
  GeometryIsSmall                             = Yes
  Shadow                                      = SHADOW_DECAL
  ShadowSizeX                                 = 19;
  ShadowSizeY                                 = 19;
  ShadowTexture                               = ShadowI;
End
